# Generated by Django 4.2 on 2023-05-03 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0002_remove_garbagecollector_user_and_more"),
        ("accounts", "0003_garbagecollector_customerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="customer_location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="garbage_app.location",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="garbage_collector_location",
            field=models.ManyToManyField(
                blank=True, related_name="my_locations", to="garbage_app.location"
            ),
        ),
    ]
