# Generated by Django 4.2 on 2023-05-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_company_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(name="garbagecollector", managers=[],),
        migrations.AlterField(
            model_name="garbagecollector",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
