# Generated by Django 4.2 on 2023-05-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0002_remove_garbagecollector_user_and_more"),
        ("accounts", "0005_alter_garbagecollector_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="customer_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="garbage_app.location",
            ),
        ),
        migrations.AlterField(
            model_name="garbagecollector",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
