# Generated by Django 4.2 on 2023-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_customer_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
