# Generated by Django 4.2 on 2023-05-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_garbagecollector_customerprofile"),
        ("garbage_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="garbagecollector", name="user",),
        migrations.AlterField(
            model_name="collectionplan",
            name="garbage_collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.garbagecollector",
            ),
        ),
        migrations.AlterField(
            model_name="collectionrequest",
            name="garbage_collector",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.garbagecollector",
            ),
        ),
        migrations.DeleteModel(name="CustomerProfile",),
        migrations.DeleteModel(name="GarbageCollector",),
    ]
