# Generated by Django 4.2 on 2023-05-05 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0002_remove_garbagecollector_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 5, 5, 20, 2, 12, 259530, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
