# Generated by Django 4.2 on 2023-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0004_remove_collectionplan_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("FORTNIGHTLY", "Fortnightly"),
                    ("MONTHLY", "Monthly"),
                ],
                default="MONTHLY",
                max_length=40,
            ),
        ),
    ]
