# Generated by Django 4.2 on 2023-05-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_company_name'),
        ('garbage_app', '0005_alter_collectionplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='garbage_collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.garbagecollector'),
        ),
    ]
