# Generated by Django 4.2 on 2023-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0006_alter_collectionrequest_garbage_collector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
