# Generated by Django 4.2 on 2023-05-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0007_alter_collectionrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionrequest",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
