# Generated by Django 4.2 on 2023-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0010_alter_collectionplan_garbage_collector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionplan", options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="collectionrequest", options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
