# Generated by Django 4.2 on 2023-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0011_alter_collectionplan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionplan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectionplan",
            name="weight",
            field=models.CharField(blank=True, null=True),
        ),
    ]
