# Generated by Django 4.2 on 2023-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_app", "0012_collectionplan_description_collectionplan_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionplan",
            name="weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
